default[:netvault][:file] = "netvault-R2014APR29-SECRETARIAT-V10-Linux-Pure64-ClientOnly.tar.gz"
default[:netvault][:url] = "https://s3.amazonaws.com/pharmmd-public/netvault-R2014APR29-SECRETARIAT-V10-Linux-Pure64-ClientOnly.tar.gz"
default[:netvault][:pkg_base] = "/usr/local/netvault"
default[:netvault][:password] = "PMDSupPorT123"
default[:netvault][:language] = "English"
